apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-app
  namespace: urlshortner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
      - name: app
        image: shawkyfaried/urlshortner:latest
        ports:
        - containerPort: 8080
        env:
          - name: REDIS_ADDR
            value: "redis-service:6379"
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017"
          - name: BASE_URL
            value: "http://nginx-service"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: urlshortner
spec:
  selector:
    app: urlshortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: None  
